CREATE TABLE conversations (
                               id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                               client_id BIGINT NOT NULL,
                               recipient_id BIGINT NOT NULL,
                               CONSTRAINT fk_conversations_client FOREIGN KEY (client_id) REFERENCES clients (id),
                               CONSTRAINT fk_conversations_recipient FOREIGN KEY (recipient_id) REFERENCES recipients (id)
);

CREATE INDEX idx_conversations_client ON conversations (client_id);
CREATE INDEX idx_conversations_recipient ON conversations (recipient_id);
