CREATE TABLE clients (
                         id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                         name VARCHAR(255) NOT NULL,
                         document_id VARCHAR(255) NOT NULL,
                         document_type VARCHAR(255) NOT NULL,
                         plan_type VARCHAR(255) NOT NULL,
                         balance NUMERIC(12, 2) NOT NULL DEFAULT 0.00,
                         credit_limit NUMERIC(12, 2) NOT NULL DEFAULT 0.00,
                         active BOOLEAN NOT NULL DEFAULT TRUE,
                         version BIGINT NOT NULL DEFAULT 0,
                         CONSTRAINT uk_clients_document_id UNIQUE (document_id),
                         CONSTRAINT ck_clients_balance_nonnegative CHECK (balance >= 0),
                         CONSTRAINT ck_clients_credit_limit_nonnegative CHECK (credit_limit >= 0)
);
