CREATE TABLE messages (
                          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          conversation_id BIGINT NOT NULL,
                          sender_id BIGINT NOT NULL,
                          content VARCHAR(2000) NOT NULL,
                          created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
                          priority VARCHAR(255) NOT NULL,
                          status VARCHAR(255) NOT NULL DEFAULT 'QUEUED',
                          cost NUMERIC(12, 2) NOT NULL,
                          channel VARCHAR(255) NOT NULL,
                          CONSTRAINT fk_messages_conversation FOREIGN KEY (conversation_id) REFERENCES conversations (id),
                          CONSTRAINT fk_messages_sender FOREIGN KEY (sender_id) REFERENCES clients (id),
                          CONSTRAINT ck_messages_cost_positive CHECK (cost > 0),
                          CONSTRAINT ck_messages_priority CHECK (priority IN ('NORMAL', 'URGENT')),
                          CONSTRAINT ck_messages_status CHECK (status IN ('QUEUED', 'PROCESSING', 'SENT', 'DELIVERED', 'READ', 'FAILED')),
                          CONSTRAINT ck_messages_channel CHECK (channel IN ('SMS', 'WHATSAPP'))
);

CREATE INDEX idx_messages_conversation_created_at ON messages (conversation_id, created_at DESC, id DESC);
CREATE INDEX idx_messages_conversation_status ON messages (conversation_id, status);
CREATE INDEX idx_messages_sender ON messages (sender_id);
