CREATE TABLE transactions (
                              id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                              client_id BIGINT NOT NULL,
                              transaction_type VARCHAR(255) NOT NULL,
                              amount NUMERIC(12, 2) NOT NULL,
                              timestamp TIMESTAMP(6) WITH TIME ZONE NOT NULL,
                              message_id BIGINT,
                              CONSTRAINT fk_transactions_client FOREIGN KEY (client_id) REFERENCES clients (id),
                              CONSTRAINT fk_transactions_message FOREIGN KEY (message_id) REFERENCES messages (id),
                              CONSTRAINT uk_transactions_message UNIQUE (message_id),
                              CONSTRAINT ck_transactions_amount_positive CHECK (amount > 0),
                              CONSTRAINT ck_transactions_type CHECK (transaction_type IN ('CREDIT', 'DEBIT')),
                              CONSTRAINT ck_transactions_type_message CHECK (
                                  (transaction_type = 'CREDIT' AND message_id IS NULL)
                                      OR (transaction_type = 'DEBIT' AND message_id IS NOT NULL)
                                  )
);

CREATE INDEX idx_transactions_client_timestamp ON transactions (client_id, timestamp DESC, id DESC);
